name: Build and Push Docker Images

# 1. Trigger only on git push events
on:
  push: main                         # Runs on every push to any branch by default :contentReference[oaicite:0]{index=0}

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest 
  
  
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v2

  - name: Log in to Docker Hub
    uses: docker/login-action@v2
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: Build and push ${ matrix.service } image
    uses: docker/build-push-action@v4
    with:
      context: ./${{ matrix.service }}
      file: ./${{ matrix.service }}/Dockerfile
      push: true
      tags: |
        ${{ secrets.DOCKERHUB_USERNAME }}/spring-cloud-${{ matrix.service }}:latest
        ${{ secrets.DOCKERHUB_USERNAME }}/spring-cloud-${{ matrix.service }}:${{ github.sha }}
      platforms: linux/amd64,linux/arm64

  - name: Output image digest
    run: |
      docker buildx imagetools inspect \
        ${{ secrets.DOCKERHUB_USERNAME }}/spring-cloud-${{ matrix.service }}:latest | jq -r '.digest'
